%{
 Copyright (c) 2018 KIOS Research and Innovation Centre of Excellence
 (KIOS CoE), University of Cyprus (www.kios.org.cy)
 
 Licensed under the EUPL, Version 1.1 or – as soon they will be approved 
 by the European Commission - subsequent versions of the EUPL (the "Licence");
 You may not use this work except in compliance with theLicence.
 
 You may obtain a copy of the Licence at: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12
 
 Unless required by applicable law or agreed to in writing, software distributed
 under the Licence is distributed on an "AS IS" basis,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the Licence for the specific language governing permissions and limitations under the Licence.
 
 Author(s)     : Marinos Christoloulou, Marios Kyriakou and Alexis Kyriacou
 
 Work address  : KIOS Research Center, University of Cyprus
 email         : akyria09@ucy.ac.cy (Alexis Kyriacou)
 Website       : http://www.kios.ucy.ac.cy
 
 Last revision : June 2018
%}
function varargout = CDIParameter(varargin)


% Create the UI if one does not already exist.
% Bring the UI to the front if one does already exist.
hf = findall(0,'Tag',mfilename);
if isempty(hf)
    % Create a UI
    hf = localCreateUI(varargin);
else
    % Bring it to the front
    figure(hf);
end

% populate the output if required
if nargout > 0
    varargout{1} = hf;
end

function hf = localCreateUI(modelName)

% Create the figure, setting appropriate properties
hf = figure('Tag',mfilename,...
    'Toolbar','none',...
    'MenuBar','none',...
    'IntegerHandle','off',...
    'Units','normalized',...
    'Resize','off',...
    'NumberTitle','off',...
    'HandleVisibility','callback',...
    'Color', [240/255 240/255 239/255],...
    'Name',sprintf('CDI Parameters'),...
    'CloseRequestFcn',@localCloseRequestFcn,...
    'Visible','off');

Pos = get(hf,'Position');
set(hf,'Position',[Pos(1), Pos(2), 0.35, 0.5])

% Create a panel for operations that can be performed
hop = uipanel('Parent',hf,...
    'Units','normalized',...
    'Position',[0.015 0.08 0.97 0.85],...
    'Title','',...
    'BackgroundColor',[245/255 245/255 250/255],...
    'HighlightColor',[245/255 245/255 250/255],...
    'ShadowColor',[245/255 245/255 250/255],...
    'HandleVisibility','callback',...
    'Tag','ParameterPanel');

hop1 = uipanel('Parent',hop,...
    'Units','normalized',...
    'Position',[0.015 0.01 0.46 0.98],...
    'FontSize', 9,...
    'Title','Uncertainties Bound:',...
    'BackgroundColor',[245/255 245/255 250/255],...
    'HandleVisibility','callback',...
    'Tag','UncertaintiesPanel');

hop2 = uipanel('Parent',hop1,...
    'Units','normalized',...
    'Position',[0.01 0.75 0.98 0.15],...    
    'Title','Constant:',...
    'BackgroundColor',[245/255 245/255 250/255],...
    'HandleVisibility','callback',...
    'Tag','ConstantPanel');

hop3 = uipanel('Parent',hop1,...
    'Units','normalized',...
    'Position',[0.01 0.34 0.98 0.4],...    
    'Title','Tolerances:',...
    'BackgroundColor',[245/255 245/255 250/255],...
    'HandleVisibility','callback',...
    'Tag','TolerancePanel');

hop4 = uipanel('Parent',hop1,...
    'Units','normalized',...
    'Position',[0.01 0.13 0.98 0.2],...    
    'Title','File:',...
    'BackgroundColor',[245/255 245/255 250/255],...
    'HandleVisibility','callback',...
    'Tag','FilePanel');

hop5 = uipanel('Parent',hop,...
    'Units','normalized',...
    'Position',[0.48 0.45 0.515 0.54],...
    'FontSize', 9,...
    'Title','Detection and Isolation Parameters:',...
    'BackgroundColor',[245/255 245/255 250/255],...
    'HandleVisibility','callback',...
    'Tag','DIParametersPanel');

hop6 = uipanel('Parent',hop,...
    'Units','normalized',...
    'Position',[0.48 0.3 0.515 0.15],...
    'FontSize', 9,...
    'Title','Noise Bound:',...
    'BackgroundColor',[245/255 245/255 250/255],...
    'HandleVisibility','callback',...
    'Tag','NoiseBoundPanel');

hop7 = uipanel('Parent',hop,...
    'Units','normalized',...
    'Position',[0.48 0.01 0.515 0.29],...
    'FontSize', 9,...
    'Title','Nominal A-matrix:',...
    'BackgroundColor',[245/255 245/255 250/255],...
    'HandleVisibility','callback',...
    'Tag','NominalPanel');

strings = {'Constant','Tolerance','File'};
value = [1 0 0];
positions = [0.05 0.37 0.73];
len = [0.25 0.3 0.2];
for i = 1:3
    uicontrol('Parent',hop1,...
            'Style','radiobutton',...
            'Units','normalized',...
            'Position',[positions(i) 0.91 len(i) 0.1],...
            'String',strings{i},...
            'Enable','on',...
            'Value', value(i),...
            'Backgroundcolor',[245/255 245/255 250/255],...
            'HandleVisibility','callback',...
            'Tag',strings{i});
end

strings = {'DA:','DH:'};
Tag = {'DAtxt', 'DHtxt'};
positions = [0.03 0.48];

for i = 1:2
    uicontrol('Parent',hop2,...
            'Style','text',...
            'Units','normalized',...
            'Position',[positions(i) 0.25 0.1 0.5],...
            'String',strings{i},...
            'Enable','on',...
            'Value', value(i),...
            'Backgroundcolor',[245/255 245/255 250/255],...
            'HandleVisibility','callback',...
            'Tag',Tag{i});        
end

strings = {'0','0'};
Tag = {'DAedit', 'DHedit'};
positions = [0.14 0.59];

for i = 1:2
    uicontrol('Parent',hop2,...
            'Style','edit',...
            'Units','normalized',...
            'Position',[positions(i) 0.35 0.3 0.45],...
            'String',strings{i},...
            'Backgroundcolor','w',...
            'Enable','on',...                       
            'HandleVisibility','callback',...
            'Tag',Tag{i});        
end

strings = {'DA:','DH:'};
Tag = {'DAtxt2', 'DHtxt2'};
positions = [0.26 0.63];

for i = 1:2
    uicontrol('Parent',hop1,...
            'Style','text',...
            'Units','normalized',...
            'Position',[positions(i) 0.06 0.1 0.03],...
            'String',strings{i},...
            'Enable','on',...            
            'Backgroundcolor',[245/255 245/255 250/255],...
            'HandleVisibility','callback',...
            'Tag',Tag{i});        
end

strings = {'0','0'};
Tag = {'DAedit2', 'DHedit2'};
positions = [0.38 0.74];

for i = 1:2
    uicontrol('Parent',hop1,...
            'Style','edit',...
            'Units','normalized',...
            'Position',[positions(i) 0.05 0.25 0.055],...
            'String',strings{i},...
            'Backgroundcolor','w',...
            'Enable','on',...                       
            'HandleVisibility','callback',...
            'Tag',Tag{i});        
end

strings = {'Wind Direction:','Wind Speed:', 'Zone Temperature:', 'Path Openings:', 'Max Iterations:'};
Tag = {'WindDirectionTxt', 'WindSpeedTxt', 'ZoneTemperatureTxt', 'PathOpeningsTxt', 'MaxIterationsTxt'};
positions = [0.87 0.7 0.53 0.36 0.19];

for i = 1:5
    uicontrol('Parent',hop3,...
            'Style','text',...
            'Units','normalized',...
            'Position',[0.01 positions(i) 0.4 0.12],...
            'String',strings{i},...
            'Enable','on',...            
            'Backgroundcolor',[245/255 245/255 250/255],...
            'HorizontalAlignment','left',...
            'HandleVisibility','callback',...
            'Tag',Tag{i});        
end


uicontrol('Parent',hop1,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.03 0.05 0.24 0.06],...
        'BackgroundColor',[240/255 240/255 240/255],...
        'String','Calculate',...
        'Enable','on',...
        'Callback',@callbacks,...
        'HandleVisibility','callback',...
        'Tag','Calculate'); 
    
uicontrol('Parent',hf,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.015 0.945 0.1 0.05],...
        'BackgroundColor',[245/255 245/255 250/255],...
        'String','1',...
        'Enable','on',...
        'Callback',@callbacks,...
        'HandleVisibility','callback',...
        'Tag','Sub1');
    
   
    
for i = 1:8    
    uicontrol('Parent',hf,...
            'Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.015+0.1*i 0.945 0.1 0.05],...
            'BackgroundColor',get(hf,'Color'),...
            'String',num2str(i+1),...
            'Enable','on',...
            'Callback',@callbacks,...
            'HandleVisibility','callback',...
            'Tag',sprintf('Sub%d',i+1));
end

uicontrol('Parent',hop4,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.02 0.4 0.24 0.39],...
        'BackgroundColor',[240/255 240/255 240/255],...
        'String','Load',...
        'Enable','on',...
        'Callback',@callbacks,...
        'HandleVisibility','callback',...
        'Tag','Load');

    
uicontrol('Parent',hop4,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[0.3 0.4 0.68 0.35],...
        'String','',...
        'Backgroundcolor','w',...
        'Enable','inactive',...                       
        'HandleVisibility','callback',...
        'Tag','LoadEdit');

uicontrol('Parent',hop6,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[0.7 0.4 0.25 0.45],...
        'String','0',...
        'Backgroundcolor','w',...
        'Enable','on',...                       
        'HandleVisibility','callback',...
        'Tag','NoiseEdit');     
    
htt = uicontrol('Parent',hf,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.015 0.92 0.97 0.03],...
    'BackgroundColor',[245/255 245/255 250/255],...
    'String','',...    
    'Tag','StaticText');

uicontrol('Parent',hf,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.7 0.015 0.118 0.047],...
        'BackgroundColor',[240/255 240/255 240/255],...
        'String','OK',...
        'Enable','on',...
        'Callback',@OK,...
        'HandleVisibility','callback',...
        'Tag','OK');
    
uicontrol('Parent',hf,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',[0.82 0.015 0.118 0.047],...
        'BackgroundColor',[240/255 240/255 240/255],...
        'String','Cancel',...
        'Enable','on',...
        'Callback',@Cancel,...
        'HandleVisibility','callback',...
        'Tag','Cancel');    

% Position the UI in the centre of the screen
movegui(hf,'center')
% Make the UI visible
set(hf,'Visible','on');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Callback Function for deleting the UI
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function localCloseRequestFcn(hObject,eventdata)

% destroy the window
delete(hObject);